package server;
public enum GameError 
{
    ERR_NONE,
    ERR_INVALID_MOVE,
    ERR_INVALID_BOARD,
    ERR_INVALID_BOARD_SIZE,
    ERR_INVALID_BOARD_DIMENSIONS,
    ERR_INVALID_BOARD_CHAR,
    ERR_INVALID_BOARD_FILE,
    ERR_INVALID_BOARD_FILE_NOT_FOUND,
    ERR_INVALID_BOARD_FILE_IO,
    ERR_MOVE_ALREADY_MADE,
    ERR_INVALID_STATE,
    ERR_BAD_REQUEST,
    ERR_UNKNOWN,

}
